theme = "dracula_at_night"

[editor]
line-number = "relative"
auto-completion = false
auto-info = true
completion-trigger-len = 2
true-color = true
shell = ["zsh", "-c"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = true
git-global = true
git-ignore = true
parents = true

[editor.lsp]
display-messages = true

[editor.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'
'<' = '>'

[editor.search]
smart-case = true
wrap-around = true
